trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '2.2.x'
      includePreviewVersions: true
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/**/src/*.sln'


