
name: Xray
on:
  push:
    branches:
      - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: dotnet build ../../src/Calculator.sln /t:Rebuild

      - name: publishing
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          F_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}   
          JF_URL: ${{ secrets.JF_URL}}     
          run: dotnet nuget push "../../nuget/AspenTech.Calculator.Sample.1.0.0.nupkg" -Source ${{ secrets.JF_URL }}  -username admin -password ${{ secrets.JF_ACCESS_TOKEN }}
